

apache_default_vhost_filename: 000-default.conf
vhost_listen_ip: "*"
vhost_listen_port: 80
vhost_listen_port_ssl: 443

  #apache_create_vhosts: true


vhost_mode: 0644
apache_global_vhost_settings: |
  DirectoryIndex index.php index.html


  #dditional properties:
  #'serveradmin, serveralias, allow_override, options, extra_parameters'.


#vhosts_filename: "{{ vhosts.servername }}.conf"
#vhosts_templates: "vhost_wordpress_ssl.conf.j2"
vhost_allow_override: "All"
vhost_options: "Indexes FollowSymLinks"

vhost_vhosts_ssl: []
























