

- name: Add a system_user
  user:
    name: "{{ vhost['user'] }}"
    group: "{{ vhost['group'] }}"
    groups: "www-data"
    home: "/var/www/vhosts/{{ vhost['server_name']}}/"
    shell: /usr/sbin/nologin







#  user:
#    name: "{{ item['vhost_user'] }}"
#    group: "{{ vhosts_group }}"
#    shell: /usr/sbin/nologin

#- name: schauen was in der
#  debug:
#    msg: "{{ passwd_user}}"
#  when: passwd_user.skipped is not true


#- name: set facts when user exists
#  set_fact:
#    user_exists: true
#  when: "user['vhost_user'] in item.key"
#  with_nested:
#    - "{{ user }}"
#    - "{{ ansible_facts.getent_passwd | dict2items }}"

#  loop: "{{ ansible_facts.getent_passwd | dict2items }}"
#  loop: "{{ user }}"
#  loop_control:
#    index_var: i
#- name: debug
#  debug:
#    msg: "item {{ item }}"
#  loop: "{{ user }}"
#- name: alles holen
#  getent:
#    database: passwd
#  register: test
#- name: schauen was in passwd ist
#  debug:
#    msg: "das ist in test: {{ test }}"
#- name: Show gathered local user names only
#  debug:
#      msg: "{{ item }}"
#  loop: "{{ getent_passwd.keys() | list }}"
#  when: ansible_check_mode



#- name: falls der User nicht vorhanden ist wird er geedet
#  block:

#    - name: alles holen
#      getent:
#        database: passwd
#       # key: "{{ item['vhost_user'] }}"
#      #loop: "{{ user}}"
#      register: passwd
#    - name: add users in List if exists
#      set_fact:
#        preuseradd: "{{ preuseradd + [ item.vhost_user ] }}"
#      #when: "item.vhost_user in passwd.ansible_facts.getent_passwd"
#      loop_control:
#        index_var: i
#      when: "'item.vhost_user' in passwd.ansible_facts.getent_passwd"
#  rescue:
#    - name: Add a system_user
#      user:
#        name: "{{ item['vhost_user'] }}"
 #       group: "{{ item['vhost_group'] }}"
 #       shell: /usr/sbin/nologin
        #umask: 0027 # eventuell die other lesen geben also die 0022
#      loop: "{{ user}}"
#      loop_control:
#        index_var: i
#      register: result
#    - name: add user in a list
#      set_fact:
#        useradd: "{{ useradd + [ result.results[i].item.vhost_user ] }}"
#      loop: "{{ user}}"
#      loop_control:
#        index_var: i
#      when: result.results[i].changed is true

#- name:
#  debug:
#    msg: "{{ ansible_facts.getent_passwd }}"




#- name: Show gathered local user names only
 # debug:
 #     msg: "{{ item }}"
 # loop: "{{ getent_passwd.keys() | list }}"
 # when: ansible_check_mode

#- name: jetzt wird die variable passwd endeckt
 # debug:
 #   var: ansible_facts.getent_services


#- name: Diese Benutzer sind auf dem Zielsystem vorhanden
#  debug:
#    msg: "Diese User sind schon auf dem Zielsystem vorhanden {{ preuseradd }}"#

#- name: Das sind die hinzugefügten Nuter
#  debug:
#    msg: "Das sins die hinzugefügten Nutzer {{ useradd }}"




