- name: Add apache vhost configuration.
  template:
    src: "vhost_wordpress.conf.j2"
    dest: /etc/apache2/sites-available/{{ vhost.server_name }}.conf
    owner: "www-data"
    group: "www-data"
    mode: 0644
  notify:
    - restart apache

- name: Add vhost symlink in sites-enabled.
  file:
    src: /etc/apache2/sites-available/{{ vhost.server_name }}.conf
    dest: /etc/apache2/sites-enabled/{{ vhost.server_name }}.conf
    state: link
  notify:
    - restart apache