- include_tasks: create_wordpress_user.yaml
  when: vhost.create_vhost is defined
  loop: "{{ vhosts }}"
  loop_control:
    loop_var: vhost

- include_tasks: configure_mariadb.yaml
  when: vhost.create_vhost is defined
  loop: "{{ vhosts }}"
  loop_control:
    loop_var: vhost

- include_tasks: create_directorys.yaml
  when: vhost.create_vhost is defined
  loop: "{{ vhosts }}"
  loop_control:
    loop_var: vhost

- name: copy wordpress to DokumeentRoot
  copy:
    src: /root/wordpress/
    dest: /var/www/vhosts/{{ vhost.server_name }}/httpdocs
    remote_src: true
    directory_mode:
    owner: www-data
    group: www-data
    mode: 0744
  when: vhost.create_vhost is defined
  loop: "{{ vhosts }}"
  loop_control:
    loop_var: vhost

- name:
  template:
    src: "wp-config.php.j2"
    dest: "/var/www/vhosts/{{ vhost.server_name }}/httpdocs/wp-config.php"
    owner: www-data
    group: www-data
    mode: 0644
  when: vhost.create_vhost is defined
  loop: "{{ vhosts }}"
  loop_control:
    loop_var: vhost

- include_tasks: create_letsencrypt_certificate.yaml
  when: (vhost.enable_ssl is defined) and (vhost.create_vhost is defined)
  loop: "{{vhosts }}"
  loop_control:
    loop_var: vhost



- include_tasks: create_non_ssl_vhost.yaml
  when: (vhost.enable_ssl is undefined) and (vhost.create_vhost is defined)
  loop: "{{vhosts }}"
  loop_control:
    loop_var: vhost







