---


# Set this to `true` to forcibly update the root password.
mariadb_root_password_update: false

mariadb_enabled_on_startup: true

# Whether my.cnf should be updated on every run.
overwrite_global_mycnf: true

# The following variables have a default value depending on operating system.
mariadb_config_file: /etc/mysql/my.cnf
# mariadb_config_include_dir: /etc/my.cnf.d

# Pass in a comma-separated list of repos to use (e.g. "remi,epel"). Used only
# for RedHat systems (and derivatives).
#mariadb_enablerepo: ""


mariadb_port: "3306"
mariadb_bind_address: '0.0.0.0'
mariadb_skip_name_resolve: false
mariadb_datadir: /var/lib/mysql
#mariadb_sql_mode: ~
# The following variables have a default value depending on operating system.
# mariadb_pid_file: /var/run/mariadbd/mariadbd.pid
mariadb_socket: /var/run/mysqld/mysqld.sock

# Log file settings.
mariadb_log_file_group: mariadb

# Slow query log settings.
mariadb_slow_query_log_enabled: false
mariadb_slow_query_time: "2"
# The following variable has a default value depending on operating system.
# mariadb_slow_query_log_file: /var/log/mariadb-slow.log

# Memory settings (default values optimized ~512MB RAM).
mariadb_key_buffer_size: "256M"
mariadb_max_allowed_packet: "64M"
mariadb_table_open_cache: "256"
mariadb_sort_buffer_size: "1M"
mariadb_read_buffer_size: "1M"
mariadb_read_rnd_buffer_size: "4M"
mariadb_myisam_sort_buffer_size: "64M"
mariadb_thread_cache_size: "8"
mariadb_query_cache_type: "0"
mariadb_query_cache_size: "16M"
mariadb_query_cache_limit: "1M"
mariadb_max_connections: "151"
mariadb_tmp_table_size: "16M"
mariadb_max_heap_table_size: "16M"
mariadb_group_concat_max_len: "1024"
mariadb_join_buffer_size: "262144"

# Other settings.
mariadb_lower_case_table_names: "0"
mariadb_wait_timeout: "28800"
mariadb_event_scheduler_state: "OFF"

# InnoDB settings.
mariadb_innodb_file_per_table: "1"
# Set .._buffer_pool_size up to 80% of RAM but beware of setting too high.
mariadb_innodb_buffer_pool_size: "256M"
# Set .._log_file_size to 25% of buffer pool size.
mariadb_innodb_log_file_size: "64M"
mariadb_innodb_log_buffer_size: "8M"
mariadb_innodb_flush_log_at_trx_commit: "1"
mariadb_innodb_lock_wait_timeout: "50"

# These settings require MySQL > 5.5.
mariadb_innodb_large_prefix: "1"
mariadb_innodb_file_format: "barracuda"

# mariadbdump settings.
mariadb_mysqldump_max_allowed_packet: "64M"

# Logging settings.
mariadb_log: ""
# The following variables have a default value depending on operating system.
mariadb_log_error: /var/log/mysql/mysql.err
# mariadb_syslog_tag: mariadb

mariadb_config_include_files: []
#  - src: path/relative/to/playbook/file.cnf
#  - { src: path/relative/to/playbook/anotherfile.cnf, force: yes }


mariadb_disable_log_bin: false

# Replication settings (replication is only enabled if master/user have values).
mariadb_server_id: "1"
mariadb_max_binlog_size: "100M"
mariadb_binlog_format: "ROW"
mariadb_expire_logs_days: "10"
mariadb_replication_role: ''
mariadb_replication_master: ''
# Same keys as `mariadb_users` above.
mariadb_replication_user: []
