# für die Installation von MariaDB am besten die apt_install rolle benutzen
- include_tasks: install_mariadb.yaml
  when: packages_list is undefined

- include_tasks: secure_installation.yaml




- include_tasks: configure.yaml